### ISSUE TITLE
[help] the owl.carousel.js javascript is not included

### ISSUE THREAD

**Issue by erredeco** [comsolit/owl_slider#10]
I am using TYPO3 7.6.2 and the latest version of owl_slider. 
The owl.carousel.js file inlcuded with \ext\owl_slider\Classes\ViewHelpers\AddJsFooterInlineCodeViewHelper.php

seems not included. I had to add it via typoscript.

I am also using t3jquery and jh_magnificpopup

**Comment by larz** [comment]
We have tested the Version with 6.2.17 and 7.6.2 we can not reproduce this.
Did you check if you have config.compressJS and config.concatenateJS off?

**Comment by erredeco** [comment]
I used
```
config.concatenateJs = 1

**Comment by larz** [comment]
ok I just pushed a new version 2.3.1 with a fix for this, so you can use concatenateJS for your page.

**Comment by erredeco** [comment]
thank you again for your quick and great feedback!

**Comment by erredeco** [comment]
just for my curiosity: may I ask you why the js can't be concatenated?
