### ISSUE TITLE
OwlSlider JS File

### ISSUE THREAD

**Issue by CarstenHager** [comsolit/owl_slider#13]
Hallo,
gibt es einen Grund, warum ihr im Viewhelper die Datei  "owl.carousel.js" nicht komprimiert einbindet (owl.carousel.min.js) ?
Gibt bei PageSpeed Insights ein paar mehr Punkte

Gruß Carsten

**Comment by larz** [comment]
Gute Frage ;-)
Ja, das könnten wir ändern.

**Comment by CarstenHager** [comment]
Danke!
