### ISSUE TITLE
Improve quality of Slider-Images?

### ISSUE THREAD

**Issue by vbello104** [comsolit/owl_slider#15]
Hello there,

first of: nicely done! Very easy to install, quite awesome to use!

I have an issue regarding the image-quality of the included images in the slider.
Everything works as it should, but my images are rendered down, so they don't look like they should.
This way, the slider is not usable for me - did I overlook the part of the configuration, where i can adjust my image quality? I want them to look exactly as the files I upload.

I added a screenshot of an example - you cant overlook the bad image quality :)
![unbenannt](https://cloud.githubusercontent.com/assets/25365854/22331475/eaa554b0-e3cb-11e6-9275-6b75625f0b57.PNG)

Thanks in advance.
Kind regards
Valerio Bello

**Comment by larz** [comment]
Hi Valerio

The Image quality comes form your image-processing configuration if you use f:image in the silder templates (default extension template)

You can adjust this in the GFX section in LocalConfiguration.php globaly.

An other way is, to render the image in slider template as source or something other.
For example as <image> tag without image-processing or <f:uri.image > maybe has other properties, or you write a little viewhelper to handle this. (light VHS will do this) 

Regards, Lars

**Comment by bittner** [comment]
Is there anything else we can do about this issue? I'm closing it for now due to lack of activity.

Feel free to reopen it if you feel there is more to discuss or even fix.
