### ISSUE TITLE
Support of TYPO3 8.x

### ISSUE THREAD

**Issue by daviian** [comsolit/owl_slider#16]
Would be nice to have owl_slider supporting the new TYPO3 8.x

I have tried to just change the required cms version but currently it seems to be a problem with the TCA definition.

**Comment by SicorDev** [comment]
Submitted an upgrade for TYPO3 8 LTS and opened pull request #18 .

**Comment by SicorDev** [comment]
Another minor 8.7. fix when using translated Owlslider items: 

In /owl_slider/Configuration/TCA/tx_owlslider_domain_model_item.php

please replace both "selectSingleBox" with "selectSingle".

**Comment by bittner** [comment]
@SicorDev would you mind to place another PR for this change? Thanks in advance!

**Comment by bharatparmar** [comment]
/var/www/html/pcs8/typo3conf/ext/owl_slider/Resources/Private/Partials/owlCarouselObjectPart.html should be renamed to OwlCarouselObjectPart.html

**Comment by bittner** [comment]
PR anyone?

**Comment by comsolitag** [comment]
Version 2.5.1 released with 8.7 Support
