### ISSUE TITLE
[TYPO3 6.2.14] Incorrect integer value

### ISSUE THREAD

**Issue by jensmarquardt** [comsolit/owl_slider#17]
Hey,

I get these errors when I try to put the slider plugin on the content or create a new slider item in a storage folder. I am using `tx_gridelements` and `tx_jfmulticontent`. Any conflicts known?

**Errors**
```
SQL error: 'Incorrect integer value: '' for column 'l18n_parent' at row 1' (tt_content:NEW590840f8bbed21.46189690)
SQL error: 'Incorrect integer value: '' for column 'sys_language_uid' at row 1' (tx_owlslider_domain_model_item:NEW59083e41a12291.66846412)
```

**lastBuiltQuery**
`
INSERT INTO tt_content (CType,starttime,endtime,layout,colPos,date,header_position,header_layout,imagewidth,imageheight,imageorient,imagecols,imagecaption_position,cols,recursive,menu_type,list_type,table_bgColor,table_border,table_cellspacing,table_cellpadding,target,spaceBefore,spaceAfter,section_frame,sectionIndex,accessibility_title,accessibility_bypass_text,tx_jfmulticontent_view,tx_gridelements_backend_layout,pid,sorting,sys_language_uid,l18n_parent,header,header_link,hidden,linkToTop,fe_group,select_key,pages,categories,tx_gridelements_container,tx_gridelements_columns,l18n_diffsource,crdate,cruser_id,tstamp,t3ver_stage) VALUES ('list','0','0','0','0','0','','0','0','0','0','2','','0','0','0','owlslider_owlslider','0','0','0','0','','0','0','0','1','','','content','','382','11904','5','','','','0','0','','','','0','','0','a:24:{s:5:\"CType\";N;s:6:\"colPos\";N;s:16:\"sys_language_uid\";N;s:11:\"l18n_parent\";N;s:6:\"header\";N;s:13:\"header_layout\";N;s:15:\"header_position\";N;s:4:\"date\";N;s:11:\"header_link\";N;s:9:\"list_type\";N;s:6:\"layout\";N;s:11:\"spaceBefore\";N;s:10:\"spaceAfter\";N;s:13:\"section_frame\";N;s:6:\"hidden\";N;s:12:\"sectionIndex\";N;s:9:\"linkToTop\";N;s:8:\"fe_group\";N;s:10:\"select_key\";N;s:5:\"pages\";N;s:9:\"recursive\";N;s:10:\"categories\";N;s:25:\"tx_gridelements_container\";N;s:23:\"tx_gridelements_columns\";N;}','1493713150','12','1493713150','0')
`

**debug_backtrace**
`
TYPO3\CMS\Backend\Controller\EditDocumentController->processData#35 // TYPO3\CMS\Core\DataHandling\DataHandler->process_datamap#512 // TYPO3\CMS\Core\DataHandling\DataHandler->insertDB#1247 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_INSERTquery#6079 // TYPO3\CMS\Core\Database\DatabaseConnection->debug#218
`

**Comment by bittner** [comment]
Is this still an issue? Were you able to resolve this yourself?

**Comment by comsolitag** [comment]
@jensmarquardt,
this issue is raised by the TYPO3 Core because of your database settings. It doesn't look like this is caused by the OwlSlider extension. 

TYPO3 issue tracker: https://forge.typo3.org/issues/55020

We suspect your database is running in `STRICT_TRANS_TABLES` mode. So setting the database to the `NO_ENGINE_SUBSTITUTION` mode should fix this issue.
