### ISSUE TITLE
TYPO3 exception, if plugin is added through CE 'Insert Records' (TYPO3 v8)

### ISSUE THREAD

**Issue by sebkln** [comsolit/owl_slider#19]
When the plugin is added through a content element **'Insert Records'**, the following TYPO3 Exception occurs:

> Oops, an error occurred!
> Section "main" does not exist.

### Versions:
**owl_slider:** current master version
**TYPO3:** several minor versions of TYPO3 v8

TypoScript only contains the Static templates from fluid_styled_content and owl_slider.

In TYPO3 v7 this usage type with the exact setup works fine. Other extension's plugins can be added this way in TYPO3 v8.

**Comment by bittner** [comment]
Thanks, Sebastian, for the bug report!

Would you be willing to extend the test setup so that we can reproduce and fix the issue?

**Comment by sebkln** [comment]
Hi Peter, unfortunately I have no experience with PHP Unit Tests. But I'll gladly help in other ways.

In the meantime I have recognized that using the plugin within 'Insert Records' **does work** in TYPO3 v8, **if** you use the deprecated _css_styled_content_ for frontend rendering.
I checked the configurations but couldn't locate the reason for the error so far. I'll make further attempts.

**Comment by sebkln** [comment]
For EXT:news additional configuration for 'Insert Records' exists in _setup.txt_:

```
# Rendering of news, displayed by "Insert Record" content element
tt_content.shortcut.20.tables := addToList(tx_news_domain_model_news)
tt_content.shortcut.20.conf.tx_news_domain_model_news = USER
tt_content.shortcut.20.conf.tx_news_domain_model_news {
	userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
	extensionName = News
	pluginName = Pi1
	vendorName = GeorgRinger
	switchableControllerActions {
		News {
			1 = detail
		}
	}

	settings =< plugin.tx_news.settings
	settings {
		singleNews.field = uid
		useStdWrap = singleNews
		insertRecord = 1
	}
}
# For fluid_styled_content
tt_content.shortcut.variables.shortcuts.tables := addToList(tx_news_domain_model_news)
tt_content.shortcut.variables.shortcuts.conf.tx_news_domain_model_news < tt_content.shortcut.20.conf.tx_news_domain_model_news
```
Is it possible that something similar is needed for owl_slider? I already tested some modifications of this without success, though.

**Comment by sebkln** [comment]
This seems somehow related to [Core issue #79760](https://forge.typo3.org/issues/79760).

After renaming the FLUIDTEMPLATE's Layout name of `owl_slider` from `Default` to `DefaultLayout`, the error disappeared. No further action was required.

I'm closing this issue, but want to point out that this core issue is open since February 2017. It's your choice to wait for a core bugfix or rename the extension's Layout, which after all would be a breaking change.
