### ISSUE TITLE
Template path without function

### ISSUE THREAD

**Issue by harp71** [comsolit/owl_slider#24]
Hi, im trying to set the root-path for Layout, Templates and Partials to a fileadmin-folder. But my settings are ignored. I tried to set them in constants and setup, TS-Object-Browser shows the path correctly, but the new location is ignored?

Looks like this the in constants
plugin {
	tx_owlslider {
		...
		view { 
			templateRootPath = fileadmin/site/templates/owlslider/Private/Templates/
			partialRootPath = fileadmin/site/templates/owlslider/Private/Partials/
			layoutRootPath = fileadmin/site/templates/owlslider/Private/Layouts/
		}
		...
	}
}

Looks like this in the TS-Object-Browser Setup:
[plugin]
...
[tx_owlslider]
[view]
    [templateRootPath] = fileadmin/site/templates/owlslider/Private/Templates/
    [partialRootPath] = fileadmin/site/templates/owlslider/Private/Partials/
    [layoutRootPath] = fileadmin/site/templates/owlslider/Private/Layouts/

If i make changes in fileadmin-files nothing happens, if i change files in the EXT-folders, changes work. As if i never changed the path ...

Can somebody please help me figuring out whats wrong?

TYPO3 8.7.12
owl_slider 2.5.2

Thanks,
harP

**Comment by comsolitag** [comment]
overwrite the template like this:
plugin.tx_owlslider {
  view {

    templateRootPaths >
    templateRootPaths {
      0 = EXT:owl_slider/Resources/Private/Templates/
      1 = yourpath
    }
    partialRootPaths >
    partialRootPaths {
      0 = EXT:owl_slider/Resources/Private/Partials/
      1 = yourpath
    }
    layoutRootPaths >
    layoutRootPaths {
      0 = EXT:owl_slider/Resources/Private/Layouts/
      1 = yourpath
    }
  }

This will work

**Comment by harp71** [comment]
THX a lot
