### ISSUE TITLE
No Access tab, no starttime and endtime field

### ISSUE THREAD

**Issue by AlexandreBelec** [comsolit/owl_slider#25]
Hi!

I have a TYPO3 8.7.6 and a 2.5.2 version of owlSlider installed on it. I made an upgrade from TYPO3 7.6.x and before the upgrade, we never had that issue... but now...

When i add a slide, i can't put a start or a end time on it because the fields seem to be hidden. What's going on? Can i forgot to do something in configuration?

Can you help me please?
Alex

(Sorry for my not-too-good english, i'm french canadian ;) )

**Comment by comsolitag** [comment]
Hi Alex
Thanks for write this issue, we will check it and fix it.
Cheers Lars

**Comment by alexanderschneider** [comment]
Hi Alex,
we fixed this bug in Version 2.5.3.
