### ISSUE TITLE
Some bugs found

### ISSUE THREAD

**Issue by AlexandreBelec** [comsolit/owl_slider#26]
Hi! My colleagues and I have unfortunately found some new bugs in owl_slider version 2.5.3... Hope you can fix them... :)

1. I have a two language website (French and English). French is my default language. I can't select it in the dropdown list. View Screenshot1.

2. When I translate my slider, it has to be linked to the original slider. But when i choose Transl.Orig value in the select list, it doesn't keep my value I've chosen... View Screenshot2.

3. When I select an image already uploaded in the fileadmin, it is adding an underscore and a number to the filename. But, in the fileadmin, the image doesn't have an underscore nor of number. View Screenshot3.

4. You've fixed this bug (https://github.com/comsolit/owl_slider/issues/25) I've sent before, but when i choose an hour and a date to publish my slide and when i save it, it goes back to another date and hour 00:00... View Screenshot4.

Thank you very much!
Alex
![screenshot1](https://user-images.githubusercontent.com/38563815/40004413-a4adf694-5763-11e8-8999-7207cbbf08aa.png)
![screenshot2](https://user-images.githubusercontent.com/38563815/40004414-a4e2d79c-5763-11e8-8304-1e458259bc84.png)
![screenshot3](https://user-images.githubusercontent.com/38563815/40004415-a512211e-5763-11e8-8afd-1a29bcf7528a.png)
![screenshot4](https://user-images.githubusercontent.com/38563815/40004417-a55904da-5763-11e8-9486-efd5fe3a4b43.png)

**Comment by alexanderschneider** [comment]
Hi Alex,
thank you for writing this bug report.

1. We fixed this Issue. The default language is now available on version 2.5.4.

2. Transl.Orig value is now storeable on version 2.5.4.

3. The itemimage name should be unique, it depends from typo3 core. If you've the same Image on more items, it add a underscore and a number, that increments the more same images you have.

4. This Issue doesn't work on TYPO3 version 8.7.8. It is fixed on TYPO3 version 8.7.12.
