### ISSUE TITLE
PHP Warning: Use of undefined constant

### ISSUE THREAD

**Issue by Juerg-E** [comsolit/owl_slider#29]
PHP Warning: Use of undefined constant owl_slider - assumed 'owl_slider' (this will throw an Error in a future version of PHP) in /srv/www/htdocs/typo3conf/ext/owl_slider/Classes/ViewHelpers/AddJsFooterInlineCodeViewHelper.php line 35

[ TYPO3 8.7.19 / PHP 7.2.5 / 10.2.15-MariaDB ]

**Comment by Juerg-E** [comment]
Solution: add single quotation marks

- OLD: ... siteRelPath(owl_slider) ...
- NEW: ... siteRelPath('owl_slider') ...

**Comment by tecjam** [comment]
We have just released version 3.0.0 for TYPO3 9.x which drops support for TYPO3 7 & 8.
Version 3.0.0 also fixes this issue.

Pull requests are welcome for fixes to previous major versions.
