### ISSUE TITLE
 TYPO3 9.5 compatibility

### ISSUE THREAD

**Issue by bihor** [comsolit/owl_slider#30]
I have updated the version 2.5.4 so it is now compatible with TYPO3 9.5.
Are you interested in that version?
You could compare it e.g. with WinMerge.

**Comment by comsolitag** [comment]
We have this version already, I have pushed the 3.0.0 already

**Comment by bihor** [comment]
OK, I have tested it, but the rte_ckeditor works for me only if I add this line
'enableRichtext' => true,
to the TCA at itemcontent like described here:
https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Text.html
See line 182 in tx_owlslider_domain_model_item.php
