### ISSUE TITLE
Ordering customizable per TypoScript

### ISSUE THREAD

**Issue by inrivagmbh** [comsolit/owl_slider#4]
Grüezi! Would it be possible to add a TS option to select the order of the owl slider items to be ASC or DESC? By default it seems to be "Z-A". Now using js to modify it. Jochen

**Comment by crazedT** [comment]
Hi Jochen,
the item ordering depends on how the items are ordered in the backend. But you are right, it really would be nice to have a TS option. I will take it into consideration for the next version.
![owl_order](https://cloud.githubusercontent.com/assets/7015090/8872039/2e9711ac-31fa-11e5-818e-d1e46a0584f3.jpg)
