### ISSUE TITLE
[help] I can't use the functionality "Custom settings for each slider on page"

### ISSUE THREAD

**Issue by erredeco** [comsolit/owl_slider#9]
I am using TYPO3 7.6.2 and the latest version of owl_slider.
The example in the documentation seems wrong (template analyzer reports it as an error)... I tried with both:
```
plugin.tx_owlslider.settings.predef.example {
name = Example settings {
items = 2 
random = true 
navigation = true
}
}
```
and
```
plugin.tx_owlslider.settings.predef.example {
name = Example settings 
items = 2 
random = true 
navigation = true
}
```
whithout results.

How can I change the string `predef.example` string? can I write `plugin.tx_owlslider.settings.whatever` or `plugin.tx_owlslider.settings.test` ?

**Comment by larz** [comment]
I'm sorry the "rst doc reader" has broken this part of the documentation.
It shoud be:
 
plugin.tx_owlslider {
 settings {

        autoPlay = true
        singleItem = true

        predef {

          home {
                name = home
                settings {
                    random = true
                }
            }

            spezial {
                name = spezial
                settings {
                    singleItem = false
                    items = 6
                    random = true
                }
             }
        }

    }
}

**Comment by erredeco** [comment]
so the "trick" is:

```
plugin.tx_owlslider.settings .predef.[STRING]{

            name = [STRING]
            settings {
                //your settings
            }
}
```
where `[STRING]` must be the same in the two places? that works :)
thank you for your feedback

**Comment by larz** [comment]
Yes exactly!
